import type { Metadata } from "next";
import { Inter, Outfit, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Reusables/Footer";

const inter = Inter({ subsets: ["latin"] });

const outfit = Outfit({subsets : ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
        <Footer />
      </body>

    </html>
  );
}
